server:
  port: 20004
web:
 upload-path: D:/hongrenquan/
file:
  maxsize: 10240
spring:
  application:
    name: @artifactId@
  #数据源配置
  datasource:
    url: ${ray.datasource.url}
    username: ${ray.datasource.username}
    password: ${ray.datasource.password}

    servlet:
      multipart:
        # 根据实际需求作调整
        # 默认最大上传文件大小为1M，单个文件大小
        max-file-size: 10MB
        # 默认最大请求大小为10M，总上传的数据大小
        max-request-size: 15MB