server:
  port: 20003
spring:
  application:
    name: ${artifactId}
  #数据源配置
  datasource:
    url: ${ray.datasource.url}
    username: ${ray.datasource.username}
    password: ${ray.datasource.password}
  cloud:
    nacos:
      discovery:
  #        ip: 139.9.203.15
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        hbm2ddl:
          auto: update  #         指定DDL mode (none, validate, update, create, create-drop)
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

wechat:
  appid: wx3d1fc01c88aeb1b3
  appsecret: e5381ab9b059e91c94fc5ecf2f651d63
  mchid: 1608136320 # 商户号
  api_v3_key: adfsaf # 商户APIv3密钥
  merchant_serial_number: adfsaf  # 商户证书序列号
  notify_url: https://hrq.houxinghua.com/ # 通知地址

dubbo:
  scan:
    base-packages: hqsc.ray.wcc.feign
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registries:
    new:
      address: spring-cloud://localhost
#  registry:
#   The Spring Cloud Dubbo's registry extension
#    address: spring-cloud://localhost
#   The traditional Dubbo's registry
#    address: nacos://127.0.0.1:8848

#jetcach配置
jetcache:
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: redis://${spring.redis.host}:${spring.redis.port}/
      #uri:
      #  - redis://127.0.0.1:7000
      #  - redis://127.0.0.1:7001
      #  - redis://127.0.0.1:7002
      #readFrom: slavePreferred

## 配置日志显示在spring boot admin
logging:
  file:
    name: logs/app/ray-system/ray-system.log

mybatis-plus:
  configuration:
    call-setters-on-nulls: true
