#服务器配置
server:
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
    io-threads: 4
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
    worker-threads: 20
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

#spring配置
spring:
  devtools:
    restart:
      log-condition-evaluation-delta: false
    livereload:
      port: 23333
  main:
    allow-bean-definition-overriding: true

#feign配置
feign:
  hystrix:
    enabled: true
    #sentinel:
    #enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
#对外暴露端口
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
#knife4j 2.0.6+配置参数
knife4j:
  enable: true
  setting:
    enableReloadCacheParameter: true